### ISSUE TITLE
JSON file doesn't validate as JSON

### ISSUE THREAD

**Issue by ghost** [tedchoward/tidbits#1]
I ran the JSON file through DuckDuckGo's instant JSON validator and received the following results:

```
Error: Parse error on line 12:
..."  },  "items": [{% for post in site.p
---------------------^
Expecting 'STRING', '}', got 'undefined'
```

It would seem the file extension `json` is actually a `liquid` template for Jekyll. Is there a specific reason `json` is used instead of leveraging Ruby to generate a bona fide `liquid` template?

**Comment by tedchoward** [comment]
You are correct, the the files with `json` extensions are `liquid` templates, as are the files with `html` extensions and even `rss.xml`. The generated files are served from http://tidbits.tedchoward.com

I'm not sure I understand your question. This is a Jekyll blog. The I generate the JSON feeds similarly to how I generate the RSS feeds.

**Comment by ghost** [comment]
I guess it's kinda like JSX using a JS extension. OK.
