### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by ghost** [tedchoward/tidbits#2]
The liquid file created to produce the JSON file does not contain any unit tests. What happens if someone modifies the JSON file and produces an invalid JSON feed? Do the readers fail completely or is there some sort of invalid syntax resilience built into the readers so they can handle invalid JSON syntax or botched feed elements?

**Comment by tedchoward** [comment]
It probably fails spectacularly. This code has one purpose: to generate my blog. I have it here on Github primarily as an archive for me. If someone else can benefit from reading the source, I think that's great. But this is not software that I'm releasing or supporting.

**Comment by ghost** [comment]
Thanks for the info, @tedchoward. I landed here from the JSONFeed website. They were promoting your work. Sorry for the noise.

**Comment by tedchoward** [comment]
Don't worry about it. I didn't realize it was linked from anywhere.

Use it as a reference. Copy it into your project if you like. It does work. It's just not something I'm supporting as I would released software.
